services:

    #
    # Routing event listeners
    #

    ms.rpc.route_loader:
        class: MS\RpcBundle\Route\Loader
        tags:
            - { name: routing.loader }

    ms.rpc.request_listener:
        class: MS\RpcBundle\EventListener\RequestListener
        arguments: [ "@ms.rpc.request_factory", "@router.default" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 34 }

    ms.rpc.response_listener:
        class: MS\RpcBundle\EventListener\ResponseListener
        arguments: [ "@ms.rpc.response_factory", "@serializer" ]
        tags:
            - { name: kernel.event_listener, event: kernel.view      }
            - { name: kernel.event_listener, event: kernel.exception }


    #
    # Normalizers
    #

    ms.rpc.serializer.name_converter.soap:
        class: MS\RpcBundle\Serializer\NameConverter\SoapNameConverter

    ms.rpc.serializer.normalizer.date_time:
        class: MS\RpcBundle\Serializer\Normalizer\DateTimeNormalizer
        tags:
            - { name: serializer.normalizer, priority: -100 }

    ms.rpc.serializer.normalizer.rpc:
        class: MS\RpcBundle\Serializer\Normalizer\RpcNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.jsend:
        class: MS\RpcBundle\Serializer\Normalizer\JSendNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.json_rpc_xs:
        class: MS\RpcBundle\Serializer\Normalizer\JsonRpcXSNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.json_wsp:
        class: MS\RpcBundle\Serializer\Normalizer\JsonWSPNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.rest:
        class: MS\RpcBundle\Serializer\Normalizer\RestNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.soap:
        class: MS\RpcBundle\Serializer\Normalizer\SoapNormalizer
        arguments: [ ~, "@ms.rpc.serializer.name_converter.soap", "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    ms.rpc.serializer.normalizer.xml_rpc:
        class: MS\RpcBundle\Serializer\Normalizer\XmlRpcNormalizer
        arguments: [ ~, ~, "@ms.property_info.extractor" ]
        tags:
            - { name: serializer.normalizer }

    #
    # Encoders
    #

    ms.rpc.serializer.encoder.rpc:
        class: MS\RpcBundle\Serializer\Encoder\RpcEncoder
        tags:
            - { name: serializer.encoder }

    ms.rpc.serializer.encoder.soap:
        class: MS\RpcBundle\Serializer\Encoder\SoapEncoder
        tags:
            - { name: serializer.encoder }

    ms.rpc.serializer.encoder.xml_rpc:
        class: MS\RpcBundle\Serializer\Encoder\XmlRpcEncoder
        tags:
            - { name: serializer.encoder }

    #
    # Factories
    #

    ms.rpc.request_factory:
        class: MS\RpcBundle\Factory\RequestFactory
        arguments: [ "@serializer" ]

    ms.rpc.response_factory:
        class: MS\RpcBundle\Factory\ResponseFactory
        arguments: [ "@serializer" ]

    #
    # REST Service
    #

    ms.rpc.rest:
        class: MS\RpcBundle\Service\RestService
        arguments: [ "@doctrine.orm.entity_manager_default" ]
